### ISSUE TITLE
Error installing 2.12.0-RC1

### ISSUE THREAD

**Issue by Giraudierpierre** [SplashSync/Sylius-Bundle#18]
Hello. I encounter an error when installing release 2.12.0-RC1 on sylius 1.11.

`Fatal error: Uncaught Error: Failed opening required '/home/sylius/vendor/composer/../splash/sylius-splash-plugin/vendor/splash/phpcore/inc/Splash.Inc.php'.`

The path is wrong as there is no `vendor` directory in `sylius-splash-plugin`.
Is it possible to fix it?

Thank you.

**Comment by BadPixxel** [comment]
Hi,

Sorry this is just for CI/CD testing. Please try again with 2.12.0-RC2

Thanks

**Comment by Giraudierpierre** [comment]
Thanks for release 2.12.0-RC2. 
The installation works well but I encounter an error with the connection to the database. The Splash\SyliusSplashPlugin\Services\ProductTranslationManager service uses a sylius repository to retrieve the locales, which causes problems when reinstalling the database.

![image](https://user-images.githubusercontent.com/25774748/230398311-ad6d8177-bbaf-406e-afb3-0964445784c8.png)

Thanks.

**Comment by BadPixxel** [comment]
Hi,

Can you please share more details to reproduce the error?

BR

**Comment by Giraudierpierre** [comment]
I'm trying to install your plugin in a Sylius 1.11 project based on symfony 5.
The project uses orm doctrine and doctrine migrations.
When reinstalling the database, the service container tries to call localeRepository but migrations are not yet run, i.e. the database is empty.

**Comment by BadPixxel** [comment]
Hi,

We pushed V2.12.0-RC3 with a fix for this error.

BR

**Comment by Giraudierpierre** [comment]
Hello

Thank you for V2.12.0-RC3.
However, there is still a problem with repository injection. 
In ProductTranslationsManager.php, it is injected in __construct() function which involves the same issue.
I think the call to the repository should be moved in the body of getLocales() function like this :

`public function getLocales(): array  
{  
     return $this->localesRepository->findAll();  
}`

BR
